[velox]
build_args = ['-trimpath', '-ldflags', '-s -X github.com/roadrunner-server/roadrunner/v2/internal/meta.version=v2.10.5 -X github.com/roadrunner-server/roadrunner/v2/internal/meta.buildTime=10:00:00']

[roadrunner]
ref = "v2.10.1"

[github]
[github.token]
token = ""

[github.plugins]
# ref -> master, commit or tag
logger = { ref = "master", owner = "roadrunner-server", repository = "logger" }
server = { ref = "master", owner = "roadrunner-server", repository = "server" }
http = { ref = "master", owner = "roadrunner-server", repository = "http" }
my_custom_plugin = { ref = "master", owner = "roadrunner-server", repository = "plugin_sample" }

[log]
level = "debug"
mode = "development"